SPHINXBUILD = sphinx-build
SOURCEDIR = source
BUILDDIR = build

.PHONY: html

html:
	$(SPHINXBUILD) -b html -D language=en $(SOURCEDIR) $(BUILDDIR)/en
	$(SPHINXBUILD) -b html -D language=es $(SOURCEDIR) $(BUILDDIR)/es
	$(SPHINXBUILD) -b html -D language=fr $(SOURCEDIR) $(BUILDDIR)/fr
	$(SPHINXBUILD) -b html -D language=pt_BR $(SOURCEDIR) $(BUILDDIR)/pt_BR
	$(SPHINXBUILD) -b html -D language=de $(SOURCEDIR) $(BUILDDIR)/de
	$(SPHINXBUILD) -b html -D language=af $(SOURCEDIR) $(BUILDDIR)/af
